# Date-based categorization rules
# Use this for transactions with generic descriptions that need to be categorized
# based on the date of the transaction.
#
# You can specify a full date (YYYY-MM-DD) or just a month (MM) or a day (DD).
# If only a month is specified, the rule will apply to that month in any year.
# If only a day is specified, it will apply to that day of any month and year.

date_based_rules:
  - description_contains: "PAYPAL *PYPL PAYIN ON 08 MAY BCC"
    date: "2026-05-11"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 24 APR BCC"
    date: "2026-04-27"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 08 APR BCC"
    date: "2026-04-09"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL PAYMENT 5HBJ22287DSNA DDR"
    date: "2026-04-20"
    category: "Travel"
  - description_contains: "PAYPAL *PYPL PAYIN ON 24 MAR BCC"
    date: "2026-03-25"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 08 MAR BCC"
    date: "2026-03-10"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 25 FEB BCC"
    date: "2026-02-26"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 09 JAN BCC"
    date: "2026-01-12"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 09 DEC BCC"
    date: "2025-12-10"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 09 NOV BCC"
    date: "2025-11-11"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL PAYMENT 5HBJ22287DSNA DDR"
    date: "2025-12-17"
    category: "Phone & Internet"
  - description_contains: "PAYPAL PAYMENT 5HBJ22287DSNA DDR"
    date: "2025-11-20"
    category: "Mental Health"
  - description_contains: "PAYPAL PAYMENT 5HBJ22287DSNA DDR"
    date: "2025-11-19"
    category: "Phone & Internet"
  - description_contains: "PAYPAL *PYPL PAYIN ON 04 AUG BCC"
    date: "2024-08-05"
    category: "Government Fees"
  - description_contains: "PAYPAL *PYPL PAYIN ON 03 JUL BCC"
    date: "2024-07-05"
    category: "Government Fees"
  - description_contains: "PAYPAL *PYPL PAYIN ON 04 SEP BCC"
    date: "2024-09-05"
    category: "Government Fees"
  - description_contains: "PAYPAL *PYPL PAYIN ON 21 MAY BCC"
    date: "2025-05-23"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 21 APR BCC"
    date: "2025-04-23"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 22 MAR BCC"
    date: "2025-03-24"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 14 JUN BCC"
    date: "2025-06-16"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 13 JUL BCC"
    date: "2025-07-15"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 13 AUG BCC"
    date: "2025-08-15"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 24 NOV BCC"
    date: "2024-11-25"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 24 DEC BCC"
    date: "2024-12-27"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL *PYPL PAYIN ON 24 JAN BCC"
    date: "2025-01-27"
    category: "Clothing & Accessories"
  - description_contains: "PAYPAL PAYMENT 5HBJ22287DSNA DDR"
    date: "2024-09-12"
    category: "Mental Health"
  - description_contains: "PAYPAL PAYMENT 5HBJ22287DSNA DDR"
    date: "2025-12-31"
    category: "Mental Health"
