filters:
  barclays:
    - "Trading 212"
    - "FREETRADE LIMITED"
    - "AMR AFIFIY MONZO"
    - "AMERICAN EXP"
    - "TRADING TWOONETWO"
    - "Amr Afifiy Sent from Revolut BGC"
    - "AMR AFIFIY OBAXG8BCJOS7QPD16"
    - "B/CARD REWARDS"
    - "MOHAMED RAMADAN MO AMRS LOAN FT"
    - "SAID M thanks BGC"
    - "MOHAMED SHAABAN TRANSFER RETURN FT"
    - "Mohamed Shaaban Sent from Revolut BGC"
    - "PAYPAL *GOOGLE GOO"
    - "AMR AFIFIY MONZO"
    - "Ehab Tawfik Youtube BGC"
    - "4929136093776005"
    - "PISP928531259"
    - "BLOOM LP WAGES"
    - "JAQUELINE JOSEFINA"
    - "GOOGLE UK LTD 00523342"
  monzo:
    - "BARCLAYS"
    - "MONZO"
    - "Ehab Tawfik"
    - "Mohamed Shaaban"
    - "Khaled Abdalla"
    - "Mohamed Hassaan"
    - "Mohamed Said"
  revolut_usd:
    - "Withdrawing savings"
    - "Exchanged to GBP"
    - "Depositing savings"
    - "Payment from AMR MAHMOUD ABDELGHANY AHMED AFIFIY"
    - "Flight Network Uk"
    - "Balance migration to another region or legal entity"
  revolut_gbp:
    - "TRADING TWOONETWO"
    - "Exchanged to GBP"
    - "To Amr Afifiy"
    - "Open banking top-up"
    - "Depositing savings"
    - "Withdrawing savings"
    - "Balance migration to another region or legal entity"
  amex:
    - "PAYMENT RECEIVED - THANK YOU"
  barclays_card:
    - "Barclaycard Cashback"
